version: "3"

services:
  database:
    container_name: database
    image: podcastindex/database
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    networks:
      - podcastindex

  blockstorage:
    container_name: blockstorage
    image: podcastindex/blockstorage
    build:
      context: blockstorage
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    networks:
      - podcastindex

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - podcastindex

  bus:
    container_name: bus
    image: podcastindex/bus
    build:
      context: bus
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://bus:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "podcastindex:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - podcastindex

networks:
  podcastindex:
    driver: bridge
